@startuml
'https://plantuml.com/sequence-diagram
class Buch {
  - titel: String
  - hatFortsetzung: boolean
  - genre: String
  - bewertung: int

  + getTitel(): String
  + toString(): String
}



class BuchEingabe {
   + speichern(): void
 }

 class BuchAusgabe {
   - buchListe: ArrayList<Buch>
   + anzeigen(): void
   + filtern(): void
   + sortieren(): void
 }

 BuchAusgabe o-- "1..*" Buch : enthält
 BuchEingabe --> Buch : erstellt

 note right of Buch
   Legende:
   + public
   - private
   # protected
   ~ package-private
 end note
@enduml

